package:
  name: geometric-smote
  version: "0.2.0"

source:
  url: "https://files.pythonhosted.org/packages/32/88/8b6ec534ac64b822af1692bafa375274f76796b2f84ad9dc1633956bcf94/geometric-smote-0.2.0.tar.gz"
  sha256: "4d779c48d09d786b21328fba6f8b405a6fb1304dad528978d67cb0310b360956"

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - scipy >=0.17
    - numpy >=1.1
    - scikit-learn >=0.23
    - imbalanced-learn >=0.7.0
  run:
    - python
    - scipy >=0.17
    - numpy >=1.1
    - scikit-learn >=0.23
    - imbalanced-learn >=0.7.0

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - gsmote

about:
  home: "https://github.com/georgedouzas/geometric-smote"
  license: "MIT"
  license_file: "LICENSE"
